import type { DashboardData } from '../types/dashboard.types.ts'

export const MOCK_DASHBOARD_DATA: DashboardData = {
  userName: 'Mariana',
  currentMonth: 'JUNIO',
  summary: {
    netBalance: 2_745_100,
    totalIncome: 5_200_000,
    totalExpenses: 2_454_900,
    totalDebts: 9_300_000,
    debtRatio: 48,
    incomeTrend: 6,
    expenseTrend: -3,
  },
  categorySpend: [
    { name: 'Vivienda', amount: 1_400_000 },
    { name: 'Alimentos', amount: 380_000 },
    { name: 'Servicios', amount: 340_000 },
    { name: 'Transporte', amount: 222_000 },
    { name: 'Ocio', amount: 112_900 },
  ],
  recentTransactions: [
    {
      id: '1',
      name: 'Salario LegalSuite',
      category: 'Salario',
      type: 'income',
      paymentMethod: 'Transferencia',
      date: '01 Jun',
      amount: 3_200_000,
    },
    {
      id: '2',
      name: 'Arriendo apartamento',
      category: 'Vivienda',
      type: 'expense',
      paymentMethod: 'PSE',
      date: '02 Jun',
      amount: -1_400_000,
    },
    {
      id: '3',
      name: 'Internet hogar',
      category: 'Servicios',
      type: 'expense',
      paymentMethod: 'Débito',
      date: '03 Jun',
      amount: -120_000,
    },
    {
      id: '4',
      name: 'Otros',
      category: 'Ingreso',
      type: 'income',
      paymentMethod: 'Transferencia',
      date: '05 Jun',
      amount: 1_200_000,
    },
    {
      id: '5',
      name: 'Servicios públicos',
      category: 'Servicios',
      type: 'expense',
      paymentMethod: 'PSE',
      date: '07 Jun',
      amount: -220_000,
    },
    {
      id: '6',
      name: 'Mercado quincena',
      category: 'Alimentos',
      type: 'expense',
      paymentMethod: 'Tarjeta',
      date: '12 Jun',
      amount: -380_000,
    },
    {
      id: '7',
      name: 'Proyecto Marca Vega',
      category: 'Freelance',
      type: 'income',
      paymentMethod: 'PayPal',
      date: '12 Jun',
      amount: 800_000,
    },
    {
      id: '8',
      name: 'Cena cumpleaños',
      category: 'Ocio',
      type: 'expense',
      paymentMethod: 'Tarjeta',
      date: '15 Jun',
      amount: -95_000,
    },
  ],
}
