import type { TransactionsData } from '../types/transactions.types.ts'

export const MOCK_TRANSACTIONS: TransactionsData = {
  summary: {
    totalIncome: 5_200_000,
    totalExpenses: 2_454_900,
    expenseRatio: 47,
    month: 'JUNIO',
    incomeSources: [
      { label: 'Salario', amount: 3_200_000 },
      { label: 'Freelance', amount: 800_000 },
      { label: 'Otros', amount: 1_200_000 },
    ],
  },
  transactions: [
    {
      id: '1',
      name: 'Arriendo',
      category: 'Vivienda',
      type: 'expense',
      date: '01 Jun',
      amount: 1_400_000,
    },
    {
      id: '2',
      name: 'Mercado quincena',
      category: 'Alimentos',
      type: 'expense',
      date: '12 Jun',
      amount: 380_000,
    },
    {
      id: '3',
      name: 'Servicios públicos',
      category: 'Servicios',
      type: 'expense',
      date: '07 Jun',
      amount: 220_000,
    },
    {
      id: '4',
      name: 'Gasolina',
      category: 'Transporte',
      type: 'expense',
      date: '08 Jun',
      amount: 180_000,
    },
    {
      id: '5',
      name: 'Internet hogar',
      category: 'Servicios',
      type: 'expense',
      date: '03 Jun',
      amount: 120_000,
    },
    {
      id: '6',
      name: 'Cena cumpleaños',
      category: 'Ocio',
      type: 'expense',
      date: '15 Jun',
      amount: 95_000,
    },
    {
      id: '7',
      name: 'Uber',
      category: 'Transporte',
      type: 'expense',
      date: '14 Jun',
      amount: 42_000,
    },
    { id: '8', name: 'Spotify', category: 'Ocio', type: 'expense', date: '02 Jun', amount: 17_900 },
    {
      id: '9',
      name: 'Salario LegalSuite',
      category: 'Salario',
      type: 'income',
      date: '01 Jun',
      amount: 3_200_000,
    },
    {
      id: '10',
      name: 'Proyecto Marca Vega',
      category: 'Freelance',
      type: 'income',
      date: '12 Jun',
      amount: 800_000,
    },
    {
      id: '11',
      name: 'Otros',
      category: 'Otros',
      type: 'income',
      date: '05 Jun',
      amount: 1_200_000,
    },
  ],
}
