import type { DebtsData } from '../types/debts.types.ts'

export const MOCK_DEBTS: DebtsData = {
  summary: {
    loadScore: 11,
    scoreLabel: 'SALUDABLE',
    totalActiveDebt: 9_280_000,
    totalMonthlyInterest: 195_360,
    minPaymentTotal: 550_000,
    activeCount: 3,
    paidCount: 1,
  },
  debts: [
    {
      id: '1',
      kind: 'card',
      name: 'Visa Bancolombia',
      issuer: 'BANCOLOMBIA',
      balance: 1_500_000,
      totalDebt: 2_200_000,
      monthlyRate: 3.1,
      annualRate: 44.2,
      minPayment: 75_000,
      monthlyInterest: 46_500,
      status: 'active',
      cutDay: 15,
    },
    {
      id: '2',
      kind: 'loan',
      name: 'Crédito de Libre Inversión',
      issuer: 'DAVIVIENDA',
      balance: 6_800_000,
      totalDebt: 12_000_000,
      monthlyRate: 1.8,
      annualRate: 23.9,
      minPayment: 410_000,
      monthlyInterest: 122_400,
      status: 'active',
      remainingMonths: 36,
      originalMonths: 60,
    },
    {
      id: '3',
      kind: 'card',
      name: 'Mastercard Gold',
      issuer: 'BBVA',
      balance: 980_000,
      totalDebt: 1_200_000,
      monthlyRate: 2.8,
      annualRate: 39.1,
      minPayment: 65_000,
      monthlyInterest: 27_440,
      status: 'active',
      cutDay: 20,
    },
    {
      id: '4',
      kind: 'loan',
      name: 'Crédito de vehículo',
      issuer: 'BANCOLOMBIA',
      balance: 0,
      totalDebt: 15_000_000,
      monthlyRate: 1.5,
      annualRate: 19.6,
      minPayment: 0,
      monthlyInterest: 0,
      status: 'paid',
      remainingMonths: 0,
      originalMonths: 48,
    },
  ],
}
